### DISCUSSION TITLE
Welcome to Hugo Theme Icarus-Lite Discussions

### DISCUSSION THREAD

**Discussion by airinghost** [airinghost/hugo-theme-icarus-lite#1] [Announcements]
## Hello, World!

You are welcome to

  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.

**Comment by xiamuguizhi** [comment]
我今天移植了这个主题到自己博客了，哈哈，感觉明天就能上线了，就是又要迁移一次文章了 哈哈 ，超级喜欢的主题。没想到拖到现在才来折腾 哈哈

**Reply by airinghost** [reply]
😆

**Reply by xiamuguizhi** [reply]
@airinghost 我把图片改居中显示了，在添加了一下阴影，当然代码是百度来的 哈哈。

```css
.text img{
    display: block;
    max-width: 100%;
    border-radius: 2px;
    margin: 18px auto;
	box-shadow: 0 0 4px rgba(0,0,0,0.5);
    overflow: visible;
    border-radius:12px;
    -webkit-filter: drop-shadow(4px 4px 8px rgba(0,0,0,.5)); 
    filter: drop-shadow(4px 4px 10px rgba(0,0,0,.5));
}
```

![image](https://user-images.githubusercontent.com/19650297/194873670-652db5df-0be6-400a-80e7-c706a49a2b91.png)


网站LOGO本来我也学你用表情svg图案，后面感觉感换了自己头像，哈哈。
